/* ============================================================
   ⚠ SYNTHETIC FIXTURE DATA — NOT MEASUREMENTS. ⚠
   Every business, phone number, address, agency and agency price below is
   INVENTED, for frontend development before the pipeline exists. The three
   real domains (blitzglobe, happyhomesinteriors, bestinterior) have real
   names but FABRICATED signals. Never treat any figure here as observed,
   never export it as a lead, never quote a price from it.
   Tier/score shown are hand-authored; the real values come from
   lib-scoring.js. See spec/MASTER.md §5.

   PROSPECTOR — sample phase-one output
   Shape mirrors what the real pipeline writes to disk:
     data/<vertical>/<domain>/{signals,links,contacts,verdict}.json
   Tier + score come from `judge`; reviews[] is yours, stored
   separately so the two can be compared.
   ============================================================ */

const SYNTHETIC = true;   // guard: real runs must never load this file

const VERTICALS = [
  { slug:'interior-design', label:'Interior Design', city:'Coimbatore',
    keywords:['interior designer','interior decorator','modular kitchen','false ceiling','turnkey interiors'],
    discovered:212, withDomain:147, audited:124 },
  { slug:'clinics', label:'Clinics & Polyclinics', city:'Coimbatore',
    keywords:['multispeciality clinic','polyclinic','family physician'],
    discovered:288, withDomain:96, audited:81 },
  { slug:'dental', label:'Dental', city:'Coimbatore',
    keywords:['dental clinic','orthodontist','implant dentist'],
    discovered:194, withDomain:118, audited:103 },
];

/* ---- the three from your screenshots, judged on measured signals ---- */

const LEADS = [

{
  vertical:'interior-design', domain:'blitzglobe.com', name:'Blitz Globe Interior Architect',
  mock:'blitzglobe', rating:4.6, reviews:87, address:'Sathy Road, Ganapathy, Coimbatore 641006',
  score:91, tier:'A',
  signals:{
    copyright:'2019', jquery:'1.12.4', bootstrap:'3.3.7',
    slider:'revslider 5.2', wayback:'2015', redesigned:'never',
    viewport:'missing', overflow:'+142px', tapTargets:'19 under 44px',
    lcp:'8.4s', pageWeight:'11.2 MB', heroVideo:'6.1 MB mp4, autoplay',
    https:'ok', mixedContent:'3 assets', brokenImages:'2',
    whatsapp:'present', quoteForm:'mailto: only', blog:'last post 2021',
    domainAge:'11 yr', generator:'WordPress 4.9.8', theme:'interico (ThemeForest)',
  },
  bad:['viewport','overflow','lcp','slider','redesigned','mixedContent','jquery','heroVideo'],
  reasons:[
    'Revolution Slider 5.2 and jQuery 1.12 date the build to 2015–16; Wayback shows no visual change since first snapshot.',
    'No viewport meta and 142px of horizontal overflow at 390px — the gallery, which is the product, is unusable on a phone.',
    '6.1 MB autoplaying hero video pushes LCP to 8.4s on 4G. Most local traffic is mobile.',
    'WordPress 4.9.8 with mixed content on 3 assets: security nag as a secondary angle.',
    'Ability to pay is proven — paid agency template build, ₹ spent on WhatsApp integration and an active quote flow.',
  ],
  angle:'Your gallery is your product, and on a phone it runs off the side of the screen. That is where most of your enquiries are coming from.',
  contacts:[
    {kind:'phone', value:'+91 91596 95555', owner:'business'},
    {kind:'email', value:'info@blitzglobe.com', owner:'business'},
    {kind:'instagram', value:'@blitzglobe', owner:'business'},
  ],
  agency:{name:'Aabasoft Technologies', domain:'aabasoft.com', credit:'Designed & Maintained by Aabasoft'},
  links:{total:64, internal:41, external:19, nav:7, footer:28, dead:3, socials:5},
  review:{tier:'A', pitch:true, note:'Best lead of the batch. Send the 390px screenshot as-is.'},
},

{
  vertical:'interior-design', domain:'happyhomesinteriors.com', name:'Happy Homes Interiors Works & Designing',
  mock:'happyhomes', rating:4.8, reviews:52, address:'Vadavalli, Coimbatore 641041',
  score:84, tier:'A',
  signals:{
    copyright:'2021', jquery:'2.2.4', bootstrap:'4.0.0',
    slider:'owl carousel 2', wayback:'2018', redesigned:'2021',
    viewport:'present', overflow:'+38px', tapTargets:'11 under 44px',
    lcp:'6.2s', pageWeight:'8.4 MB', heroVideo:'none',
    https:'ok', mixedContent:'none', brokenImages:'0',
    whatsapp:'float button', quoteForm:'GET A QUOTE → form', blog:'none',
    domainAge:'8 yr', generator:'WordPress 5.8', theme:'custom child theme',
  },
  bad:['overflow','lcp','jquery','slider','tapTargets','pageWeight'],
  reasons:[
    'Owl Carousel hero and jQuery 2.2 place the visual language around 2018; last redesign 2021 but structure unchanged.',
    '8.4 MB of uncompressed kitchen renders — LCP 6.2s. The photography is genuinely good and the site is hiding it.',
    'Floating social rail plus WhatsApp float plus a live quote form: this business actively buys leads, so ROI framing will land.',
    'Topbar crams phone, address, hours and email above the fold; 11 tap targets under 44px on mobile.',
    'Strongest ability-to-pay signal in the set — 4.8 stars over 52 reviews and a paid custom child theme.',
  ],
  angle:'Your renders are the best of any interior firm in Coimbatore and they take six seconds to appear. Compress and restructure and you keep the visitors you are already paying to attract.',
  contacts:[
    {kind:'phone', value:'+91 99943 11447', owner:'business'},
    {kind:'email', value:'happyhomesinteriorscbe@gmail.com', owner:'business'},
    {kind:'hours', value:'Mon–Sat 8:00–22:00', owner:'business'},
  ],
  agency:{name:'Webcastle Media', domain:'webcastle.in', credit:'Website by Webcastle'},
  links:{total:81, internal:58, external:23, nav:9, footer:34, dead:1, socials:6},
  review:{tier:'A', pitch:true, note:'Gmail address on a real domain — owner-run, decision in one call.'},
},

{
  vertical:'interior-design', domain:'bestinterior.co', name:'Best Interior',
  mock:'bestinterior', rating:4.1, reviews:6, address:'Not published',
  score:38, tier:'C',
  signals:{
    copyright:'none', jquery:'none', bootstrap:'none',
    slider:'none', wayback:'2025', redesigned:'n/a',
    viewport:'present', overflow:'0px', tapTargets:'2 under 44px',
    lcp:'2.1s', pageWeight:'1.3 MB', heroVideo:'none',
    https:'ok', mixedContent:'none', brokenImages:'0',
    whatsapp:'none', quoteForm:'none', blog:'none',
    domainAge:'4 mo', generator:'AI site builder', theme:'builder default',
  },
  bad:['whatsapp','quoteForm','domainAge','reviews','generator'],
  reasons:[
    'Domain registered 4 months ago, first Wayback snapshot 2025, generator string is an AI site builder — nobody has ever paid for this site.',
    'Single AI-generated stock illustration as hero; tan-on-brown body text near the contrast floor; one condensed display face doing every job.',
    'Technically fine — fast, responsive, no overflow. The problem is taste, not engineering, so the measurable pain is low.',
    'No WhatsApp, no enquiry form, no phone on the homepage: not currently buying leads.',
    'Ability to pay reads near zero. Ugliest page in the batch and the weakest prospect in it.',
  ],
  angle:'Weak. Free-tier builder, 6 reviews, no lead capture. Low ability to pay — revisit only if they start advertising.',
  contacts:[{kind:'email', value:'hello@bestinterior.co', owner:'business'}],
  agency:null,
  links:{total:11, internal:8, external:3, nav:4, footer:2, dead:0, socials:1},
  review:{tier:'X', pitch:false, note:'Agreed — ugly but broke. LLM was generous at C.'},
},

/* ---- remainder of the interior-design run ---- */

{ vertical:'interior-design', domain:'srivarudhiniinteriors.com', name:'Sri Varudhini Interiors',
  mock:'generic-dated', rating:4.7, reviews:64, address:'Peelamedu, Coimbatore 641004',
  score:88, tier:'A',
  signals:{copyright:'2017', jquery:'1.11.3', bootstrap:'3.3.5', slider:'nivo slider',
    wayback:'2014', redesigned:'never', viewport:'missing', overflow:'+310px',
    tapTargets:'24 under 44px', lcp:'9.8s', pageWeight:'14.6 MB', heroVideo:'none',
    https:'expired 2024-11', mixedContent:'12 assets', brokenImages:'5',
    whatsapp:'present', quoteForm:'php form', blog:'none', domainAge:'12 yr',
    generator:'static html', theme:'hand-coded tables'},
  bad:['https','viewport','overflow','lcp','brokenImages','mixedContent','redesigned','jquery'],
  reasons:[
    'TLS certificate expired November 2024 — browsers show a full interstitial before anyone sees the site. Urgent and trivially provable.',
    'Table-based layout, Nivo Slider, jQuery 1.11: unchanged since the 2014 first snapshot.',
    '310px overflow at 390px and 5 broken images. 64 reviews at 4.7 says the business is healthy while the site is not.',
  ],
  angle:'Your site currently shows a security warning before anyone reaches it. That is costing you every mobile enquiry today.',
  contacts:[{kind:'phone', value:'+91 98422 54xxx', owner:'business'},{kind:'email', value:'info@srivarudhini.com', owner:'business'}],
  agency:{name:'Cbe Web Solutions', domain:'cbewebsolutions.in', credit:'Site by CBE Web Solutions'},
  links:{total:47, internal:33, external:14, nav:6, footer:19, dead:7, socials:3},
  review:{tier:'A', pitch:true, note:'Expired cert = opening line writes itself.'} },

{ vertical:'interior-design', domain:'dreamspaceinteriorscbe.in', name:'Dream Space Interiors',
  mock:'generic-dated', rating:4.4, reviews:38, address:'Saibaba Colony, Coimbatore 641011',
  score:79, tier:'B',
  signals:{copyright:'2020', jquery:'3.4.1', bootstrap:'4.3.1', slider:'swiper 4',
    wayback:'2019', redesigned:'2020', viewport:'present', overflow:'+12px',
    tapTargets:'8 under 44px', lcp:'5.4s', pageWeight:'6.1 MB', heroVideo:'none',
    https:'ok', mixedContent:'none', brokenImages:'1',
    whatsapp:'float button', quoteForm:'contact form 7', blog:'last post 2022',
    domainAge:'7 yr', generator:'WordPress 6.1', theme:'astra + elementor'},
  bad:['lcp','pageWeight','tapTargets','blog'],
  reasons:[
    'Elementor build from 2020 — dated but not broken. Pain is moderate: slow, heavy, generic template.',
    'Real lead capture in place (CF7 + WhatsApp float) so the ROI conversation is available.',
    'Warm rather than hot: no single flaw is dramatic enough to open cold.',
  ],
  angle:'Everything works, nothing stands out. Sell differentiation, not repair — their competitors all run the same Elementor template.',
  contacts:[{kind:'phone', value:'+91 90478 11xxx', owner:'business'},{kind:'email', value:'dreamspacecbe@gmail.com', owner:'business'}],
  agency:{name:'Aabasoft Technologies', domain:'aabasoft.com', credit:'Powered by Aabasoft'},
  links:{total:59, internal:44, external:15, nav:8, footer:22, dead:0, socials:4},
  review:{tier:'B', pitch:true, note:'Second wave. Lead with competitor-template angle.'} },

{ vertical:'interior-design', domain:'kovaimodularkitchen.com', name:'Kovai Modular Kitchen',
  mock:'generic-dated', rating:4.5, reviews:71, address:'Gandhipuram, Coimbatore 641012',
  score:86, tier:'A',
  signals:{copyright:'2016', jquery:'1.12.4', bootstrap:'3.3.7', slider:'revslider 4.6',
    wayback:'2016', redesigned:'never', viewport:'missing', overflow:'+205px',
    tapTargets:'22 under 44px', lcp:'7.9s', pageWeight:'9.8 MB', heroVideo:'none',
    https:'ok', mixedContent:'6 assets', brokenImages:'3',
    whatsapp:'present', quoteForm:'mailto: only', blog:'none', domainAge:'10 yr',
    generator:'WordPress 4.7.1', theme:'kitchen-pro (ThemeForest)'},
  bad:['viewport','overflow','lcp','redesigned','jquery','slider','brokenImages'],
  reasons:[
    'Nine years on the same ThemeForest kitchen template, no viewport meta, 205px overflow.',
    'WordPress 4.7.1 is eight years unpatched — real security exposure, useful as urgency.',
    '71 reviews at 4.5: strong, established, clearly has budget.',
  ],
  angle:'Modular kitchens sell on photographs. Yours are 900px wide on a template from 2016 and they crop badly on every phone.',
  contacts:[{kind:'phone', value:'+91 94430 22xxx', owner:'business'},{kind:'email', value:'sales@kovaimodular.com', owner:'business'}],
  agency:{name:'Cbe Web Solutions', domain:'cbewebsolutions.in', credit:'Designed by CBE Web Solutions'},
  links:{total:52, internal:38, external:14, nav:7, footer:21, dead:4, socials:3},
  review:{tier:'A', pitch:true, note:''} },

{ vertical:'interior-design', domain:'elegantinteriors-cbe.com', name:'Elegant Interiors',
  mock:'generic-dated', rating:4.2, reviews:23, address:'R.S. Puram, Coimbatore 641002',
  score:72, tier:'B',
  signals:{copyright:'2018', jquery:'1.12.4', bootstrap:'3.3.7', slider:'owl carousel 1',
    wayback:'2017', redesigned:'never', viewport:'present', overflow:'+64px',
    tapTargets:'14 under 44px', lcp:'6.8s', pageWeight:'7.2 MB', heroVideo:'none',
    https:'ok', mixedContent:'2 assets', brokenImages:'1',
    whatsapp:'none', quoteForm:'php form', blog:'none', domainAge:'9 yr',
    generator:'WordPress 5.2', theme:'betheme'},
  bad:['overflow','lcp','jquery','redesigned','whatsapp'],
  reasons:[
    'BeTheme build from 2017, never redesigned. Dated but stable.',
    'No WhatsApp button and a bare PHP form — weaker signal that they are chasing leads.',
    '23 reviews puts ability to pay in the middle band.',
  ],
  angle:'No WhatsApp, no enquiry tracking. Start with lead capture, redesign as the follow-on.',
  contacts:[{kind:'phone', value:'+91 97878 44xxx', owner:'business'}],
  agency:null,
  links:{total:41, internal:31, external:10, nav:6, footer:16, dead:2, socials:2},
  review:{tier:'B', pitch:false, note:''} },

{ vertical:'interior-design', domain:'aksharainteriors.in', name:'Akshara Interiors & Decor',
  mock:'generic-dated', rating:4.9, reviews:112, address:'Race Course, Coimbatore 641018',
  score:83, tier:'A',
  signals:{copyright:'2019', jquery:'2.1.4', bootstrap:'4.1.3', slider:'slick 1.8',
    wayback:'2016', redesigned:'2019', viewport:'present', overflow:'+22px',
    tapTargets:'9 under 44px', lcp:'5.9s', pageWeight:'7.8 MB', heroVideo:'none',
    https:'ok', mixedContent:'none', brokenImages:'0',
    whatsapp:'float button', quoteForm:'wpforms', blog:'last post 2023',
    domainAge:'9 yr', generator:'WordPress 6.0', theme:'divi'},
  bad:['lcp','pageWeight','jquery','tapTargets'],
  reasons:[
    '112 reviews at 4.9 is the strongest ability-to-pay signal in the whole run — this is a substantial firm.',
    'Divi build from 2019: heavy, slow, visually generic, but nothing is broken.',
    'Pain is moderate and ability to pay is very high, so the product multiplies well.',
  ],
  angle:'You are the highest-rated interior firm in Coimbatore and your site looks like everyone else\'s. That gap is the pitch.',
  contacts:[{kind:'phone', value:'+91 99655 78xxx', owner:'business'},{kind:'email', value:'contact@aksharainteriors.in', owner:'business'},{kind:'instagram', value:'@aksharainteriors', owner:'business'}],
  agency:{name:'Webcastle Media', domain:'webcastle.in', credit:'Crafted by Webcastle'},
  links:{total:73, internal:54, external:19, nav:8, footer:29, dead:0, socials:5},
  review:{tier:'A', pitch:true, note:'Highest ability to pay. Lead with brand gap, not bugs.'} },

{ vertical:'interior-design', domain:'urbannest-interior.com', name:'Urban Nest Interior Studio',
  mock:'generic-modern', rating:4.6, reviews:31, address:'Avinashi Road, Coimbatore 641014',
  score:34, tier:'X',
  signals:{copyright:'2025', jquery:'none', bootstrap:'none', slider:'embla',
    wayback:'2024', redesigned:'2025', viewport:'present', overflow:'0px',
    tapTargets:'0 under 44px', lcp:'1.6s', pageWeight:'1.1 MB', heroVideo:'none',
    https:'ok', mixedContent:'none', brokenImages:'0',
    whatsapp:'float button', quoteForm:'react form', blog:'active',
    domainAge:'2 yr', generator:'Next.js 14', theme:'custom'},
  bad:[],
  reasons:[
    'Redesigned in 2025 on Next.js 14 — fast, responsive, accessible, actively maintained.',
    'Zero measurable pain. Nothing to sell.',
    'Skip. Re-check in 18 months.',
  ],
  angle:'No pain. Skip.',
  contacts:[{kind:'phone', value:'+91 93456 12xxx', owner:'business'}],
  agency:null,
  links:{total:38, internal:30, external:8, nav:5, footer:14, dead:0, socials:3},
  review:{tier:'X', pitch:false, note:''} },

{ vertical:'interior-design', domain:'lakshmifalseceiling.co.in', name:'Lakshmi False Ceiling Works',
  mock:'generic-dated', rating:4.3, reviews:17, address:'Ukkadam, Coimbatore 641001',
  score:58, tier:'C',
  signals:{copyright:'2015', jquery:'1.9.1', bootstrap:'2.3.2', slider:'jquery cycle',
    wayback:'2013', redesigned:'never', viewport:'missing', overflow:'+420px',
    tapTargets:'31 under 44px', lcp:'11.2s', pageWeight:'16.9 MB', heroVideo:'none',
    https:'none — http only', mixedContent:'n/a', brokenImages:'9',
    whatsapp:'none', quoteForm:'none', blog:'none', domainAge:'13 yr',
    generator:'static html', theme:'frontpage export'},
  bad:['https','viewport','overflow','lcp','brokenImages','jquery','whatsapp','quoteForm'],
  reasons:[
    'Worst technical state in the run — HTTP only, 420px overflow, 9 broken images, LCP 11.2s.',
    'But 17 reviews and a single-trade operation: ability to pay is the constraint, not willingness.',
    'Maximum pain × low budget. Offer a one-page rebuild at a fixed low price or leave it.',
  ],
  angle:'Pain is total, budget is not. Fixed-price single-pager only.',
  contacts:[{kind:'phone', value:'+91 95001 66xxx', owner:'business'}],
  agency:null,
  links:{total:19, internal:14, external:5, nav:5, footer:6, dead:8, socials:0},
  review:{tier:'C', pitch:false, note:'Good portfolio piece if they pay anything at all.'} },

{ vertical:'interior-design', domain:'thehomestudio.co.in', name:'The Home Studio',
  mock:'generic-dated', rating:4.5, reviews:44, address:'Kalapatti, Coimbatore 641048',
  score:76, tier:'B',
  signals:{copyright:'2019', jquery:'3.3.1', bootstrap:'4.3.1', slider:'owl carousel 2',
    wayback:'2017', redesigned:'2019', viewport:'present', overflow:'+48px',
    tapTargets:'12 under 44px', lcp:'6.4s', pageWeight:'8.9 MB', heroVideo:'2.2 MB mp4',
    https:'ok', mixedContent:'1 asset', brokenImages:'0',
    whatsapp:'present', quoteForm:'contact form 7', blog:'last post 2020',
    domainAge:'8 yr', generator:'WordPress 5.9', theme:'the7'},
  bad:['lcp','overflow','pageWeight','heroVideo','blog'],
  reasons:[
    'The7 theme, 2019 build. Standard dated-but-functional profile.',
    'Autoplaying 2.2 MB hero video on mobile burns data before the first paint.',
    '44 reviews at 4.5 — comfortable mid-tier budget.',
  ],
  angle:'Your hero video costs mobile visitors 2 MB before they see a single kitchen.',
  contacts:[{kind:'phone', value:'+91 98945 33xxx', owner:'business'},{kind:'email', value:'hello@thehomestudio.co.in', owner:'business'}],
  agency:{name:'Pixel Frame Studio', domain:'pixelframe.co.in', credit:'Developed by Pixel Frame'},
  links:{total:56, internal:41, external:15, nav:7, footer:23, dead:1, socials:4},
  review:{tier:'B', pitch:false, note:''} },

{ vertical:'interior-design', domain:'greenleafinteriors.net', name:'Green Leaf Interiors',
  mock:'generic-dated', rating:3.9, reviews:9, address:'Sundarapuram, Coimbatore 641024',
  score:46, tier:'C',
  signals:{copyright:'2014', jquery:'1.10.2', bootstrap:'3.0.0', slider:'flexslider',
    wayback:'2014', redesigned:'never', viewport:'missing', overflow:'+280px',
    tapTargets:'27 under 44px', lcp:'10.1s', pageWeight:'12.4 MB', heroVideo:'none',
    https:'ok', mixedContent:'8 assets', brokenImages:'6',
    whatsapp:'none', quoteForm:'mailto: only', blog:'none', domainAge:'12 yr',
    generator:'WordPress 4.4', theme:'unknown'},
  bad:['viewport','overflow','lcp','brokenImages','mixedContent','jquery','whatsapp'],
  reasons:[
    'Abandoned in 2014 and technically broken throughout.',
    '9 reviews at 3.9 — the business itself may be dormant. Verify it still trades before spending time.',
  ],
  angle:'Check if still operating before contacting.',
  contacts:[{kind:'email', value:'greenleaf.cbe@yahoo.co.in', owner:'business'}],
  agency:null,
  links:{total:24, internal:18, external:6, nav:5, footer:9, dead:6, socials:1},
  review:{tier:null, pitch:false, note:''} },

{ vertical:'interior-design', domain:'ssinteriordesigners.in', name:'S.S. Interior Designers',
  mock:'generic-dated', rating:4.7, reviews:58, address:'Thudiyalur, Coimbatore 641034',
  score:81, tier:'A',
  signals:{copyright:'2018', jquery:'1.12.4', bootstrap:'3.3.7', slider:'revslider 5.0',
    wayback:'2016', redesigned:'never', viewport:'missing', overflow:'+168px',
    tapTargets:'20 under 44px', lcp:'7.2s', pageWeight:'10.1 MB', heroVideo:'none',
    https:'ok', mixedContent:'4 assets', brokenImages:'2',
    whatsapp:'float button', quoteForm:'wpforms', blog:'none', domainAge:'10 yr',
    generator:'WordPress 5.4', theme:'interio (ThemeForest)'},
  bad:['viewport','overflow','lcp','redesigned','jquery','slider'],
  reasons:[
    'Same ThemeForest family as Blitz Globe and Kovai — one agency template, three clients.',
    'No viewport meta, 168px overflow, active WhatsApp and form.',
    '58 reviews at 4.7: solid budget, proven spend.',
  ],
  angle:'Three of your competitors in Coimbatore run the identical template. Here they are side by side.',
  contacts:[{kind:'phone', value:'+91 94881 90xxx', owner:'business'},{kind:'email', value:'ssinteriors.cbe@gmail.com', owner:'business'}],
  agency:{name:'Cbe Web Solutions', domain:'cbewebsolutions.in', credit:'Designed by CBE Web Solutions'},
  links:{total:49, internal:36, external:13, nav:7, footer:18, dead:2, socials:3},
  review:{tier:null, pitch:false, note:''} },

{ vertical:'interior-design', domain:'vaasthuinteriors.com', name:'Vaasthu Interiors & Architects',
  mock:'generic-dated', rating:4.4, reviews:29, address:'Singanallur, Coimbatore 641005',
  score:69, tier:'B',
  signals:{copyright:'2020', jquery:'3.5.1', bootstrap:'4.5.0', slider:'swiper 6',
    wayback:'2018', redesigned:'2020', viewport:'present', overflow:'+8px',
    tapTargets:'6 under 44px', lcp:'4.8s', pageWeight:'5.2 MB', heroVideo:'none',
    https:'ok', mixedContent:'none', brokenImages:'0',
    whatsapp:'float button', quoteForm:'contact form 7', blog:'last post 2024',
    domainAge:'8 yr', generator:'WordPress 6.2', theme:'astra'},
  bad:['lcp','pageWeight'],
  reasons:[
    'Maintained Astra build, 2020. Mild staleness, no breakage.',
    'Low-pain warm lead. Worth a soft touch, not a cold pitch.',
  ],
  angle:'Low pain. Nurture only.',
  contacts:[{kind:'phone', value:'+91 90922 45xxx', owner:'business'},{kind:'email', value:'info@vaasthuinteriors.com', owner:'business'}],
  agency:null,
  links:{total:51, internal:39, external:12, nav:7, footer:20, dead:0, socials:4},
  review:{tier:null, pitch:false, note:''} },

/* ---- other verticals, to show the folder concept ---- */

{ vertical:'clinics', domain:'kovaipolyclinic.com', name:'Kovai Polyclinic',
  mock:'generic-dated', rating:4.2, reviews:143, address:'Trichy Road, Coimbatore 641018',
  score:87, tier:'A',
  signals:{copyright:'2016', jquery:'1.11.1', bootstrap:'3.2.0', slider:'nivo slider',
    wayback:'2014', redesigned:'never', viewport:'missing', overflow:'+240px',
    tapTargets:'26 under 44px', lcp:'8.8s', pageWeight:'9.1 MB', heroVideo:'none',
    https:'ok', mixedContent:'5 assets', brokenImages:'4',
    whatsapp:'none', quoteForm:'appointment form (broken)', blog:'none',
    domainAge:'12 yr', generator:'WordPress 4.5', theme:'medicare (ThemeForest)'},
  bad:['viewport','overflow','lcp','brokenImages','quoteForm','redesigned','jquery'],
  reasons:[
    'Appointment form posts to a dead endpoint — every booking attempt has failed silently for years. Provable in one screenshot.',
    '143 reviews: high-volume practice, real budget.',
    'No viewport meta on a site whose primary job is directions and booking on a phone.',
  ],
  angle:'Your appointment form has been silently failing. I filled it in and nothing arrived — here is the network log.',
  contacts:[{kind:'phone', value:'+91 422 245 xxxx', owner:'business'},{kind:'email', value:'kovaipolyclinic@gmail.com', owner:'business'}],
  agency:{name:'Cbe Web Solutions', domain:'cbewebsolutions.in', credit:'Designed by CBE Web Solutions'},
  links:{total:44, internal:34, external:10, nav:6, footer:17, dead:5, socials:2},
  review:{tier:null, pitch:false, note:''} },

{ vertical:'clinics', domain:'sreedeviclinic.in', name:'Sreedevi Clinic',
  mock:'generic-dated', rating:4.6, reviews:67, address:'Ramanathapuram, Coimbatore 641045',
  score:74, tier:'B',
  signals:{copyright:'2019', jquery:'3.4.1', bootstrap:'4.3.1', slider:'owl carousel 2',
    wayback:'2017', redesigned:'2019', viewport:'present', overflow:'+30px',
    tapTargets:'10 under 44px', lcp:'5.6s', pageWeight:'6.4 MB', heroVideo:'none',
    https:'ok', mixedContent:'none', brokenImages:'0',
    whatsapp:'float button', quoteForm:'contact form 7', blog:'none',
    domainAge:'7 yr', generator:'WordPress 5.8', theme:'astra'},
  bad:['lcp','tapTargets','pageWeight'],
  reasons:['Functional 2019 Astra build. Moderate staleness, no urgent flaw.','67 reviews — decent budget, warm not hot.'],
  angle:'Nurture. No single urgent flaw.',
  contacts:[{kind:'phone', value:'+91 422 258 xxxx', owner:'business'}],
  agency:null,
  links:{total:39, internal:30, external:9, nav:6, footer:15, dead:0, socials:3},
  review:{tier:null, pitch:false, note:''} },

{ vertical:'dental', domain:'smilecraftdental.in', name:'SmileCraft Dental Studio',
  mock:'generic-dated', rating:4.9, reviews:206, address:'D.B. Road, R.S. Puram, Coimbatore 641002',
  score:90, tier:'A',
  signals:{copyright:'2017', jquery:'1.12.4', bootstrap:'3.3.7', slider:'revslider 5.1',
    wayback:'2015', redesigned:'never', viewport:'missing', overflow:'+190px',
    tapTargets:'23 under 44px', lcp:'8.1s', pageWeight:'10.8 MB', heroVideo:'4.4 MB mp4',
    https:'ok', mixedContent:'3 assets', brokenImages:'1',
    whatsapp:'present', quoteForm:'appointment form', blog:'last post 2019',
    domainAge:'11 yr', generator:'WordPress 4.9', theme:'dentalcare (ThemeForest)'},
  bad:['viewport','overflow','lcp','redesigned','jquery','slider','heroVideo'],
  reasons:[
    '206 reviews at 4.9 — by far the highest ability to pay in the dataset. Premium practice on a 2015 template.',
    'No viewport meta, 190px overflow, 4.4 MB autoplay video.',
    'Cosmetic dentistry sells on before/after imagery and the gallery is unviewable on a phone.',
  ],
  angle:'You are the highest-rated dentist in Coimbatore and your before/after gallery does not fit on a phone screen.',
  contacts:[{kind:'phone', value:'+91 98430 77xxx', owner:'business'},{kind:'email', value:'care@smilecraftdental.in', owner:'business'},{kind:'instagram', value:'@smilecraft.cbe', owner:'business'}],
  agency:{name:'Aabasoft Technologies', domain:'aabasoft.com', credit:'Designed & Maintained by Aabasoft'},
  links:{total:68, internal:49, external:19, nav:8, footer:26, dead:2, socials:5},
  review:{tier:null, pitch:false, note:''} },

{ vertical:'dental', domain:'32pearlsdentalcare.com', name:'32 Pearls Dental Care',
  mock:'generic-dated', rating:4.5, reviews:88, address:'Saravanampatti, Coimbatore 641035',
  score:78, tier:'B',
  signals:{copyright:'2020', jquery:'3.5.1', bootstrap:'4.5.2', slider:'slick 1.8',
    wayback:'2019', redesigned:'2020', viewport:'present', overflow:'+40px',
    tapTargets:'13 under 44px', lcp:'6.0s', pageWeight:'7.4 MB', heroVideo:'none',
    https:'ok', mixedContent:'none', brokenImages:'0',
    whatsapp:'float button', quoteForm:'wpforms', blog:'last post 2023',
    domainAge:'6 yr', generator:'WordPress 6.1', theme:'divi'},
  bad:['lcp','pageWeight','tapTargets'],
  reasons:['Divi build, 2020. Generic and slow but sound.','88 reviews — good budget, moderate pain.'],
  angle:'Differentiation pitch, not repair.',
  contacts:[{kind:'phone', value:'+91 95665 12xxx', owner:'business'},{kind:'email', value:'hello@32pearls.com', owner:'business'}],
  agency:{name:'Pixel Frame Studio', domain:'pixelframe.co.in', credit:'Developed by Pixel Frame'},
  links:{total:54, internal:40, external:14, nav:7, footer:21, dead:0, socials:4},
  review:{tier:null, pitch:false, note:''} },

];

/* ---- agency inversion: who built these, and what they charge ---- */

const AGENCIES = [
  { name:'Cbe Web Solutions', domain:'cbewebsolutions.in',
    builtInRun:4, portfolioClients:38, pricing:[
      {tier:'Static 5-page', price:'₹12,000'},
      {tier:'WordPress business', price:'₹28,000'},
      {tier:'E-commerce', price:'₹65,000'},
      {tier:'AMC / yr', price:'₹6,000'},
    ],
    note:'Local floor-setter. ThemeForest resale, no design work. Their 38-client portfolio page is an expansion list.' },
  { name:'Aabasoft Technologies', domain:'aabasoft.com',
    builtInRun:3, portfolioClients:24, pricing:[
      {tier:'Starter', price:'₹18,000'},
      {tier:'Business', price:'₹45,000'},
      {tier:'Custom', price:'on request'},
    ],
    note:'Mid-market. Clients skew 2016–2019 builds still on AMC — paying monthly for a site nobody has touched.' },
  { name:'Webcastle Media', domain:'webcastle.in',
    builtInRun:2, portfolioClients:51, pricing:[
      {tier:'Not published', price:'—'},
    ],
    note:'Kerala-based, larger. No public pricing. 51 clients listed; filter to Coimbatore for the next sweep.' },
  { name:'Pixel Frame Studio', domain:'pixelframe.co.in',
    builtInRun:2, portfolioClients:16, pricing:[
      {tier:'Landing page', price:'₹8,000'},
      {tier:'Full site', price:'₹22,000'},
    ],
    note:'Cheapest local competitor. Useful as the price anchor you position above.' },
];
